import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
export const metadata = {
  title: "Next.js 15 Example",
  description: "A demo of paging and routing in Next.js 15",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            padding: "10px",
            backgroundColor: "#f4f4f4",
            textAlign: "center",
          }}
        >
          <nav>
            <a href="/" style={{ margin: "0 10px" }}>
              Home
            </a>
            <a href="/about" style={{ margin: "0 10px" }}>
              About
            </a>
            <a href="/contact" style={{ margin: "0 10px" }}>
              Contact
            </a>
            <a href="/post" style={{ margin: "0 10px" }}>
              Posts
            </a>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
